import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { emptyLedger, importCsv, readLedger, setSaleValuation } from '../src/ledger.ts';
import { annualByInstrument, annualSummary, sumDecimals, transactionValue } from '../src/annual.ts';
import { annualDisplay, computedCell } from '../src/annual-display.ts';
import { choosePrice, makePriceSeries, mergePriceSeries } from '../src/market.ts';
const csv = readFileSync(new URL('../data/sample-ml/demo.csv', import.meta.url), 'utf8');
const fixture = async () => (await importCsv(emptyLedger(), csv, 'fictional.csv')).ledger;

test('annual USD totals multiply vest quantity by price and separate cash categories', async () => {
  const l = await fixture();
  assert.deepEqual(annualSummary(l, '2023').vest, { value: '510', count: 1, missing: 0, candidates: 1 });
  const y = annualSummary(l, '2024');
  assert.equal(y.vest.value, '723.75'); assert.equal(y.dividend.value, '8.1'); assert.equal(y.withholding.value, '-1.94');
  assert.equal('referenceTotal' in y, false);
  assert.match(computedCell(l, l.transactions[2], 'en'), /8.10 USD/);
  assert.match(computedCell(l, l.transactions[3], 'en'), /-1.94 USD/);
  assert.equal(y.gain.value, '0'); assert.equal(y.gain.count, 0);
  assert.equal(annualSummary(l, '2025').gain.value, '70.527777777778');
  assert.equal(annualSummary(l, '2025').gain.missing, 0);
  assert.equal(annualSummary(l, '2025').proceeds.value, '299');
  assert.equal(annualSummary(l, 'all').vest.value, '1583.75');
  assert.match(annualDisplay(l, '2024', 'en'), /723.75/);
  assert.match(annualDisplay(l, '2024', 'ja'), /取引集計/);
  assert.match(computedCell(l, l.transactions[0], 'en'), /510 USD/);
  assert.equal(l.transactions[0].amount, '0.00');
});
test('yearly price follows imported candidates, then locks to a selected estimate', async () => {
  let l = await fixture(); const t = l.transactions[0];
  l.mappings.push({ key: t.instrumentKey, instrument: { name: 'Fictional', symbol: 'FICT', exchange: 'NASDAQ' } });
  l = mergePriceSeries(l, [await makePriceSeries('Date,Open,High,Low,Close\n2023-12-28,40,50,39,45\n', { symbol: 'FICT', exchange: 'NASDAQ', providerSymbol: 'fict.us', start: '2023-12-28', end: '2023-12-28' })]);
  assert.equal(annualSummary(l, '2023').vest.value, '540');
  l = choosePrice(l, t.id, 0);
  assert.deepEqual(annualSummary(l, '2023').vest, { value: '510', count: 1, missing: 0, candidates: 0 });
});
test('missing values, excluded rows and unresolved duplicates never silently become zero', async () => {
  let l = await fixture(); l.transactions[0].quantity = null;
  assert.equal(annualSummary(l, '2023').vest.value, null);
  assert.equal(annualSummary(l, '2023').vest.missing, 1);
  assert.equal(annualSummary(l, 'all').vest.value, '1073.75');
  l.transactions[0].excluded = true;
  assert.equal(annualSummary(l, '2023').vest.count, 0);
  l = (await importCsv(await fixture(), csv + '\n', 'overlap.csv')).ledger;
  assert.equal(annualSummary(l, '2023').vest.value, null);
  assert.equal(annualSummary(l, '2023').duplicates, 2);
  l.transactions[6].excluded = true;
  assert.equal(annualSummary(l, '2023').vest.value, '510');
});
test('gain requires documented proceeds and assigned cost; supports losses, zero cost and restore', async () => {
  let l = await fixture(); const sale = l.transactions.find(t => t.kind === 'sale')!;
  assert.equal(annualSummary(l, '2025').gain.missing, 0);
  l = setSaleValuation(l, sale.id, { proceeds: '299', cost: '212.50', evidence: 'Fictional sale statement and cost allocation' });
  l = readLedger(JSON.stringify(l));
  assert.equal(annualSummary(l, '2025').gain.value, '86.5');
  assert.match(computedCell(l, sale, 'en'), /299 USD/);
  l = setSaleValuation(l, sale.id, { proceeds: '299', cost: '350', evidence: 'Fictional loss' });
  assert.equal(annualSummary(l, '2025').gain.value, '-51');
  l = setSaleValuation(l, sale.id, { proceeds: '299', cost: '0', evidence: 'Explicit fictional zero cost' });
  assert.equal(annualSummary(l, '2025').gain.value, '299');
  for (const cost of [null, '-1']) assert.throws(() => setSaleValuation(l, sale.id, { proceeds: '299', cost, evidence: 'fixture' }));
  assert.throws(() => setSaleValuation(l, sale.id, { proceeds: '299', cost: '200', evidence: ' ' }));
  assert.throws(() => setSaleValuation(l, l.transactions[0].id, { proceeds: '299', cost: '200', evidence: 'fixture' }));
  l.mappings.push({ key: sale.instrumentKey, instrument: { name: 'Other', symbol: 'OTHER', exchange: 'NYSE' } });
  assert.equal(annualSummary(l, '2025').gain.value, '70.527777777778');
});
test('Trade Date grouping is explicit across years and unknown dates stay unassigned', async () => {
  const l = await fixture();
  l.transactions[0].lapseDate = '2022-12-31';
  assert.equal(annualSummary(l, '2023').vest.value, '510');
  assert.equal(annualSummary(l, '2022').vest.count, 0);
  l.transactions[0].tradeDate = null;
  assert.equal(annualSummary(l, '2023').vest.count, 0);
  assert.equal(annualSummary(l, '2023').unknownDates, 1);
  assert.equal(annualSummary(l, 'unknown').vest.value, '510');
});
test('old saves migrate; forged sale references are rejected and arithmetic is exact', async () => {
  const l = await fixture(); const saved = JSON.parse(JSON.stringify(l)); delete saved.saleValuations;
  assert.deepEqual(readLedger(JSON.stringify(saved)).saleValuations, []);
  const next = setSaleValuation(l, l.transactions[4].id, { proceeds: '0.3', cost: '0.2', evidence: 'fixture' });
  assert.equal(annualSummary(next, '2025').gain.value, '0.1');
  next.saleValuations[0].transactionId = 'missing';
  assert.throws(() => readLedger(JSON.stringify(next)));
  assert.equal(sumDecimals(['0.1', '0.2']), '0.3');
  assert.equal(sumDecimals(['-0.1', '-0.2', '0.3']), '0');
  assert.equal(sumDecimals(['999999999999999999.99', '0.01']), '1000000000000000000');
  assert.equal(transactionValue(l, { ...l.transactions[0], quantity: '-1' }).value, null);
});

test('employment, negative gains and dividends stay separate with instrument-level drilldowns', async () => {
  let l = await fixture();
  l = setSaleValuation(l, l.transactions[4].id, { proceeds: '299', cost: '350', evidence: 'fictional loss' });
  const summary = annualSummary(l, '2025');
  assert.equal(summary.vest.value, '350');
  assert.equal(summary.gain.value, '-51');
  assert.equal('referenceTotal' in summary, false);
  let groups = annualByInstrument(l, '2025'); assert.equal(groups.length, 2);
  assert.equal(groups.find(g => g.symbol === 'FICT')?.summary.gain.value, '-51');
  assert.equal(annualByInstrument(l, '2024')[0].summary.dividend.value, '8.1');
  const instrument = { name: 'Fictional unified <issuer>', symbol: 'FICT', exchange: 'NASDAQ' as const };
  l.mappings = [...new Set(l.transactions.map(t => t.instrumentKey))].map(key => ({ key, instrument }));
  groups = annualByInstrument(l, '2025'); assert.equal(groups.length, 1);
  assert.equal(groups[0].rows.length, 2);
  const html = annualDisplay(l, '2025', 'en');
  assert.match(html, /Employment compensation/); assert.match(html, /Share sales and dividends/);
  assert.match(html, /&lt;issuer&gt;/); assert.doesNotMatch(html, /Reference total before tax/);
  assert.match(html, /data-detail=/);
  l.transactions[4].excluded = true;
  assert.equal(annualByInstrument(l, '2025')[0].summary.gain.count, 0);
});
